// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Main$ReactTemplate = require("./containers/Main.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Main$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
